[package]
name = "c8y_smartrest"
version = "0.5.2"
authors = ["thin-edge.io team <info@thin-edge.io>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
agent_interface = { path = "../agent_interface" }
csv = "1.1"
download = { path = "../../common/download" }
serde = { version = "1.0", features = ["derive"] }
thin_edge_json = { path = "../thin_edge_json" }
thiserror = "1.0"
time = { version = "0.3", features = ["formatting", "macros", "parsing", "serde"] }

[dev-dependencies]
anyhow = "1.0"
assert_matches = "1.5"
assert-json-diff = "2.0"
serde_json = "1.0"
test-case = "1.2.1"
