name: commit-workflow

on:
  push:
    branches: [ main, continuous_integration ]
  workflow_dispatch:
    branches: [ main, continuous_integration ]
  pull_request:
    branches: [ main, continuous_integration ]

env:
  CARGO_TERM_COLOR: always

jobs:

  cargo-fmt:

    name: Run cargo fmt
    runs-on: Ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: fmt
          args: -- --check

  cargo-clippy:

    name: Run cargo clippy
    runs-on: Ubuntu-20.04

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: clippy

  cargo-test:

    name: Run cargo test
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo test
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: test
          args: --verbose

  cargo-build:

    name: Run cargo build
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo build
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: build
          args: --release

  cargo-build-integration-tests:

    name: Run cargo build for integration tests
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Compile cargo test features
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: test
          args: --verbose --no-run --features integration-test

#  cargo-build-integration-tests-single-thread:
#
#    name: Run cargo build for integration tests in one thread
#    runs-on: Ubuntu-20.04
#    needs: [cargo-fmt, cargo-clippy]
#
#    steps:
#
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: Enable cache
#        # https://github.com/marketplace/actions/rust-cache
#        uses: Swatinem/rust-cache@v1
#
#      - name: Compile cargo test features
#        uses: actions-rs/cargo@v1
#        # https://github.com/marketplace/actions/rust-cargo
#        with:
#          command: test
#          args: --verbose -- --test-threads=1 --features integration-test

  cargo-tarpaulin-avoid-cfg-tarpaulin:

    name: Run cargo tarpaulin --avoid-cfg-tarpaulin
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]
    continue-on-error: true # WTF

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust v1.54.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.54.0"
          override: true

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: install libssl
        run: sudo apt install libssl-dev

      - name: Cargo install tarpaulin
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        # Workaround see here: https://github.com/xd009642/tarpaulin/issues/756
        with:
          command: install
          args: cargo-tarpaulin
          # args: cargo-tarpaulin --version 0.18.0-alpha3

      - name: Cargo tarpaulin
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: tarpaulin
          args: --avoid-cfg-tarpaulin -v --out Xml --features integration-test

  cargo-tarpaulin:

    name: Run cargo tarpaulin
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]
    continue-on-error: true # WTF

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust v1.54.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.54.0"
          override: true

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: install libssl
        run: sudo apt install libssl-dev

      - name: Cargo install tarpaulin
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        # Workaround see here: https://github.com/xd009642/tarpaulin/issues/756
        with:
          command: install
          args: cargo-tarpaulin
          # args: cargo-tarpaulin --version 0.18.0-alpha3

      - name: Cargo tarpaulin
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: tarpaulin
          args: -v --out Xml --features integration-test

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  cargo-audit:

    name: Run cargo audit
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]


    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cargo audit
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: audit

  cargo-outdated:

    name: Run cargo outdated
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cargo outdated
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: outdated

  cargo-msrv:
    name: Run cargo msrv
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo install msrv
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: install
          args: cargo-msrv

      - name: Cargo msrv
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: msrv
          args: --minimum 1.54.0
