name: commit-workflow

on:
  push:
    branches: [ main, continuous_integration ]
  workflow_dispatch:
    branches: [ main, continuous_integration ]
  pull_request:
    branches: [ main, continuous_integration ]

env:
  CARGO_TERM_COLOR: always

jobs:
  extract:
    name: Extract
    runs-on: Ubuntu-20.04
    steps:
      - name: Extract
        run:  python3 -c 'import os; print(" ".join(os.environ["IOTHUBNAME"]))'
        env:
          IOTHUBNAME: ${{ secrets.IOTHUBNAME }}

  cargo-fmt:
    name: Run cargo fmt
    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cargo fmt --version
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: fmt
          args: --version

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: fmt
          args: -- --check

  cargo-clippy:
    name: Run cargo clippy
    runs-on: Ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo clippy --version
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: clippy
          args: --version

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: clippy

  cargo-test:
    name: Run cargo test
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo version
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: version

      - name: Cargo build dummy plugin
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: build
          args: -p tedge_dummy_plugin

      - name: Cargo test
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: test
          args: --no-fail-fast

  cargo-build:
    name: Run cargo build
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo version
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: version

      - name: Cargo build
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: build
          args: --release

  cargo-msrv:
    name: Run cargo msrv
    runs-on: Ubuntu-20.04
    needs: [cargo-fmt, cargo-clippy]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Cargo install msrv
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: install
          args: cargo-msrv

      - name: Cargo msrv --version
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: msrv
          args: --version

      - name: Cargo msrv
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: msrv
          args: --minimum 1.54.0

