name: download_offsite

on:
  workflow_dispatch:
    branches: [ main, continuous_integration]

env:
  CARGO_TERM_COLOR: always

jobs:

  hosted_offsite_dawidd6:

    runs-on: [self-hosted, Linux, ARM, offsite]

    continue-on-error: true
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: cross check with curl
          run:  curl https://api.github.com/repos/abelikt/thin-edge.io/actions/workflows/build-workflow.yml/runs?branch=continuous_integration&event=&status=success

        - name: Action dawidd6
          uses: dawidd6/action-download-artifact@v2
          # https://github.com/marketplace/actions/download-workflow-artifact
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: build-workflow.yml
            workflow_conclusion: success
            branch: continuous_integration
            name: debian-packages-amd64
            path: debian-package_unpack

  hosted_onsite_dawidd6:

    runs-on: [self-hosted, Linux, ARM] #onsite

    continue-on-error: true
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: cross check with curl
          run:  curl https://api.github.com/repos/abelikt/thin-edge.io/actions/workflows/build-workflow.yml/runs?branch=continuous_integration&event=&status=success

        - name: Action dawidd6
          uses: dawidd6/action-download-artifact@v2
          # https://github.com/marketplace/actions/download-workflow-artifact
          with:
            github_token: ${{secrets.GITHUB_TOKEN}}
            workflow: build-workflow.yml
            workflow_conclusion: success
            branch: continuous_integration
            name: debian-packages-amd64
            path: debian-package_unpack

  hosted-offsite-benday-inc:

    runs-on: [self-hosted, Linux, ARM, offsite]

    continue-on-error: true
    steps:
        - name: checkout
          uses: actions/checkout@v2

        - name: cross check with curl
          run:  curl https://api.github.com/repos/abelikt/thin-edge.io/actions/workflows/build-workflow.yml/runs?branch=continuous_integration&event=&status=success

        - name: Action benday-inc
          uses: benday-inc/download-latest-artifact@main
          # https://github.com/marketplace/actions/download-latest-artifact-from-a-github-workflow
          with:
             token: ${{ secrets.GITHUB_TOKEN }}'
             repository_owner: 'abelikt'
             repository_name: 'thin-edge.io'
             workflow_name: 'build-workflow'
             branch_name: 'continuos_integration'
             download_path: 'debian-package_unpack'
             download_filename: 'debian-packages-amd64.zip'
