name: generate-report

on:
  workflow_dispatch:
    branches: [ main, continuous_integration]

env:
  CARGO_TERM_COLOR: always

jobs:
  generate-report:
    runs-on: Ubuntu-20.04

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Generate Report
      #run:  bash ./ci/report/build.sh
      run:  bash ./ci/report/buildall.sh
      continue-on-error: false
      env:
        THEGHTOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: upload report as zip
      # https://github.com/marketplace/actions/upload-a-build-artifact
      uses: actions/upload-artifact@v2
      with:
        name: report_${{ github.run_number }}
        path: ci/report/report.zip

    - name: upload report as html
      # https://github.com/marketplace/actions/upload-a-build-artifact
      uses: actions/upload-artifact@v2
      with:
        name: system-test-report-matrix_${{ github.run_number }}
        path: ci/report/report-matrix.html


