name: generate-report

on:
  workflow_dispatch:
    branches: [ main, continuous_integration]

env:
  CARGO_TERM_COLOR: always

jobs:
  system-test_onsite:
    runs-on: [self-hosted, Linux, ARM, onsite]

    steps:

    - name: Generate Report
      run:  bash  ./ci/report/build.sh
      continue-on-error: false

    - name: upload report as zip
      # https://github.com/marketplace/actions/upload-a-build-artifact
      uses: actions/upload-artifact@v2
      with:
        name: report_${{ github.run_number }}
        path: ci/report/report.zip

