name: integration-test-workflow-stand-alone

on:
  workflow_dispatch:
    branches: [continuous_integration]
env:
  CARGO_TERM_COLOR: always

jobs:

  install-and-use-rpi:
    runs-on: [self-hosted, Linux, ARM, onsite]

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Workaround Stop collectd mapper
        run: sudo systemctl stop tedge-mapper-collectd
        continue-on-error: true

      - name: disconnect c8y
        run: sudo tedge disconnect c8y
        # We need to continue when there is no tedge already installed
        continue-on-error: true

      - name: disconnect az
        run: sudo tedge disconnect az
        # We need to continue when there is no tedge already installed
        continue-on-error: true

      - name: Run Smoke Test for Azure
        run: ./ci/ci_smoke_test_az.sh
        env:
          SASKEYQUEUE: ${{ secrets.SASKEYQUEUE }}
          SASKEYIOTHUB: ${{ secrets.SASKEYIOTHUB }}
          AZUREENDPOINT: ${{ secrets.AZUREENDPOINT }}
          AZUREEVENTHUB: ${{ secrets.AZUREEVENTHUB }}
