name: postprocess-trigger

on:
  workflow_dispatch:
    branches: [ main, continuous_integration]

#  workflow_run:
#    workflows: ["system-test-workflow"]
#    branches: [main, continuous_integration]
#    types:
#      - completed

env:
  CARGO_TERM_COLOR: always

jobs:
  postprocess:
    runs-on: Ubuntu-20.04

    steps:

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SECRET_THEGHTOKEN  }}
          event-type: custom
          repository: abelikt/thin-edge.io_analytics
