name: system-test-workflow-2

on:

  workflow_dispatch:
    branches: [ main, continuous_integration]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM]

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Run all Tests
      run:  bash  ./ci/ci_run_all_tests_2.sh
      env:
            C8YPASS: ${{ secrets.SECRET_C8YPASS }}
            C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
            C8YDEVICE: ${{ secrets.SECRET_C8YDEVICE }}
            C8YTENANT: ${{secrets.SECRET_C8YTENANT}}
            C8YDEVICEID: ${{ secrets.SECRET_C8YDEVICEID }}
            TIMEZONE: 01:00
            TEBASEDIR: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/
            EXAMPLEDIR: /home/pi/examples
            C8YURL: https://thin-edge-io.eu-latest.cumulocity.com


    - name: upload results as zip
      # https://github.com/marketplace/actions/upload-a-build-artifact
      uses: actions/upload-artifact@v2
      with:
        name: results_${{ github.run_number }}
        path: tests/
